version: "3"
services: 
  db:
    image: mysql
    environment: 
      - host="cloudflix_host",
      - user="root",
      - database="cloudflix_db",
      - password="cloudflix123",
  flask:
    build: ./flask
    environment: 
      - FLASK_ENV=development
      - FLASK_RUN_PORT=4000
      - host="cloudflix_host",
      - user="root",
      - database="cloudflix_db",
      - password="cloudflix123",
    ports: 
      - "3000:4000"
    command: python3 app.py
